### ISSUE TITLE
Cannot install via pgxn: gmake: *** No rule to make target 'pg_readme-0.3.5.control', needed by 'all'.  Stop.

### ISSUE THREAD

**Issue by autra** [bigsmoke/pg_readme#1]
Using pgenv and pgxn, I cannot install pg_readme successfully.

## Steps:

- `pgxn install pg_readme`
- observe the result

**expected**: the installation is successful

**actual**: i have the following error:

```
INFO: best version: pg_readme 0.3.5
INFO: saving /tmp/tmpz7xe6q5h/pg_readme-0.3.5.zip
INFO: unpacking: /tmp/tmpz7xe6q5h/pg_readme-0.3.5.zip
INFO: building extension
gmake: *** No rule to make target 'pg_readme-0.3.5.control', needed by 'all'.  Stop.
ERROR: command returned 2: gmake PG_CONFIG=/home/augustin/pgsql/bin/pg_config all
```

Thanks!

**Comment by autra** [comment]
There *is* a pg_readme.control file though. Maybe the MAKEFILE considers that `$EXTENSION` contains the version in this case.

**Comment by autra** [comment]
Ah yes, it's because of this: https://github.com/bigsmoke/pg_readme/blob/master/Makefile#L2

maybe extension should be hardcoded to pg_readme here? At least pg_tap does this.

**Comment by bigsmoke** [comment]
Yes, you are totally right. Thanks a lot for pointing this out. This goes to show that I so far only tested before packaging (using the `make dist` recipe), while I should have been testing the `.zip` files released to PGXN before I upload them. The directory name in the zip has the version no. in it, so I would never have been able to successfully install it if I unpacked it myself and then installed that.

I've released version 0.3.6, which should fix this. I still haven't tested using the `pgxn` client itself, but I assume it just unpacks the `.zip` and runs `make install`.

**Comment by bigsmoke** [comment]
I forgot to credit you in the commit message, @autra . Instead I did so in the [commit message](https://github.com/bigsmoke/pg_mockable/commit/89bfc12f31036686339fd078e412c96a1364f109) of the equivalent fix for `pg_mockable`.

**Comment by bigsmoke** [comment]
And I also credited you for [the fix](https://github.com/bigsmoke/pg_rowalesce/commit/6239b3d6990300da628e5450bc83574dce36e5af) in `pg_rowalesce` and `pg_utility_trigger_functions`.

**Comment by autra** [comment]
Wow thanks for the quickfix! I confirm it now installs perfectly.

> I forgot to credit you in the commit message

no problem, it's fine either way ;-)
