### ISSUE TITLE
pg_extension_readme() does not list UDFs in extension

### ISSUE THREAD

**Issue by hanefi** [bigsmoke/pg_readme#2]
First congrats on baking this extension.

I tried to test this extension on Citus extension.

On my local environment, I built pg_readme from source and installed it. I have some other extensions installed as well.

```
SELECT e.extname AS "Name", e.extversion AS "Version", n.nspname AS "Schema"
FROM pg_catalog.pg_extension e
	LEFT JOIN pg_catalog.pg_namespace n ON n.oid = e.extnamespace
	LEFT JOIN pg_catalog.pg_description c ON c.objoid = e.oid AND c.classoid = 'pg_catalog.pg_extension'::pg_catalog.regclass
ORDER BY 1;
+----------------+---------+------------+
|      Name      | Version |   Schema   |
+----------------+---------+------------+
| citus          | 11.2-1  | pg_catalog |
| citus_columnar | 11.2-1  | pg_catalog |
| hstore         | 1.8     | public     |
| pg_readme      | 0.5.5   | public     |
| plpgsql        | 1.0     | pg_catalog |
+----------------+---------+------------+
(5 rows)
```

Citus has 100+ objects: tables, UDFs, GUCs, types etc. None of them are listed on the generated readme.

```
SELECT pg_extension_readme('citus');
+------------------------------------------------------+
|                 pg_extension_readme                  |
+------------------------------------------------------+
| ---                                                 +|
| pg_extension_name: citus                            +|
| pg_extension_version: 11.2-1                        +|
| pg_readme_generated_at: 2023-01-25 16:29:23.03844+03+|
| pg_readme_version: 0.5.5                            +|
| ---                                                 +|
|                                                     +|
| Citus distributed database                           |
+------------------------------------------------------+
(1 row)
```

Do you have any pointers on how to get this working?

**Comment by bigsmoke** [comment]
I'm trying to install the citus extension locally in order to reproduce the problem, but something seems to be wrong with the Apt repository…

I'm now attempting to install from source…

**Comment by bigsmoke** [comment]
I managed to install the citus extension and was able to reproduce the problem. Now I “just” have to fix it.

**Comment by hanefi** [comment]
We use a custom repository to manage Citus packages for a while now. The packages on PGDG Apt repositories are quite outdated.

Building from source is great. If for some reason you want to get the packages you can use the steps [here](https://www.citusdata.com/download/).

I will try to help you with any problems you encounter when messing around with Citus.

Honestly, it is getting hard to keep track of documenting all the changes in Citus, and I'd be really happy if I can get pg_readme to work before our next major release.

**Comment by bigsmoke** [comment]
Ah, actually, it is behaving as documented, though I might have not made this entirely clear in the documentation. The extension is designed to place the object reference where you request it:

 ```sql
postgres=# comment on extension citus is
postgres-# $markdown$
postgres$# # Citus distributed database
postgres$#
postgres$# Citus is bla, bla bla
postgres$#
postgres$# And even more so: also fantastic.
postgres$#
postgres$# <?pg-readme-reference?>
postgres$# $markdown$;
COMMENT
```

The reason for this is that the `<?pg-readme-reference?>` processing instruction accepts a number of pseudo-attributed to control, for example, the heading level, etc. See [the documentation](https://github.com/bigsmoke/pg_readme#processing-instructions) for details.

**Comment by bigsmoke** [comment]
And I forgot to thank you for your interest in pg_readme. Thanks! 😊

**Comment by hanefi** [comment]
I can see the generated markdown now. Thanks.
